version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  install:
    commands:
      - pip install boto3
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - python --version
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
